// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10MK62kZCxfmnuKo184DnGW6tHcF3QA0',
    appId: '1:195740025252:android:5b2040f076e17ea44ac131',
    messagingSenderId: '195740025252',
    projectId: 'my-firebase-asif-taj',
    databaseURL: 'https://my-firebase-asif-taj-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-asif-taj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3erdd2r70LIpGawFR5qrIHGDUK8AKnA',
    appId: '1:195740025252:ios:d80b5d75abc6d1964ac131',
    messagingSenderId: '195740025252',
    projectId: 'my-firebase-asif-taj',
    databaseURL: 'https://my-firebase-asif-taj-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-asif-taj.appspot.com',
    androidClientId: '195740025252-54dvj8klk3mv8mhsk81iolrk4g8acjuk.apps.googleusercontent.com',
    iosClientId: '195740025252-mia9dns4e7du8gt9vv1aq357r5agrv53.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordSaver',
  );
}
